### ISSUE TITLE
Missing document for migration script when adding a new column

### ISSUE THREAD

**Issue by ndtung449** [Rhetos/Rhetos#124]
After applying Deactivatable concept to an entity, I want to write a migration script to set value for the newly added column named Active.
I have read the 'Data migration' on the wiki but still don't know how to do that. It turned out that the script generated by 'Rhetos.HelpDataMigration' missed the added column and I had to add it manually.
It would be better if your wiki page or the script generated by 'Rhetos.HelpDataMigration' mentions that. Below is my final migration script:
```
/*DATAMIGRATION 11CFA4F8-F955-4C11-A1E8-01505E27A9C6*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'MasterData', 'Partner';
EXEC Rhetos.DataMigrationUse 'MasterData', 'Partner', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'MasterData', 'Partner', 'Name', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'MasterData', 'Partner', 'Code', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'MasterData', 'Partner', 'Active', 'bit'; -- this line is added manually
GO

UPDATE _MasterData.Partner SET Active = 1 WHERE Active IS NULL

EXEC Rhetos.DataMigrationApplyMultiple 'MasterData', 'Partner', 'ID, Name, Code, Active'; -- Active is added manually
```

**Comment by bantolov** [comment]
You are right, there are some situations when the "DataMigrationUse" columns must be added manually to the scripts, for example when renaming a column (both columns are never available in the working table). We should add that to the documentation.

**Comment by bantolov** [comment]
The [Data-migration tutorial](https://github.com/Rhetos/Rhetos/wiki/Data-migration) now explains how to manually adjust the _DataMigrationUse_ and _DataMigrationApplyMultiple_ parts of this script.

Additionally, the first example includes a short walkthrough "How to write this script".
