### ISSUE TITLE
Reading web.config in module.

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#128]
I have a code which is sending emails using System.Net.Configuration.SmptSection.

var smtpSection = (System.Net.Configuration.SmtpSection)System.Configuration.ConfigurationManager.GetSection("system.net/mailSettings/smtp");
                string from = smtpSection.From;

Rhetos doesn't like this saying that:
                The type 'System.Configuration.ConfigurationSection' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

I've tried naming:
ExternalReference 'System.Configuration.ConfigurationSection, System.Configuration';
in said module, but to no avail.

**Comment by bantolov** [comment]
This seems to be an issue with the class description in `ExternalReference`.
Usually it is enough to provide **a shortened version** of the assembly qualified name (for example, `'System.Configuration.ConfigurationSection, System.Configuration`) but in this case it work only after I have used the full assembly qualified name:

```C
Module Demo
{
    Action SendMail '(parameters, repository, userInfo) =>
        {
            var smtpSection = (System.Net.Configuration.SmtpSection)System.Configuration.ConfigurationManager.GetSection("system.net/mailSettings/smtp");
            string from = smtpSection.From;
        }'
    {
        ShortString Address;
    }

    ExternalReference 'System.Configuration.ConfigurationManager, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a';
}
```

**Comment by ikudeljnj** [comment]
THis solves the problem. Thanks.
