### ISSUE TITLE
Nullable Unique concept

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#130]
Hi,

Is there a way to use Unique concept so it creates unique index on db that allows null values if Required is not specified?

DSL example:
`ShortString Signo { Unique;}`

example of index: 
CREATE UNIQUE NONCLUSTERED INDEX idx_yourcolumn_notnull
ON YourTable(yourcolumn)
WHERE yourcolumn IS NOT NULL;

**Comment by bantolov** [comment]
We could make this the default behavior for the Unique concept. I guess it is an intuitive feature for developers if the property is not required. I'm not sure if there is any performance penalty for this kind of indexes.

In a short term, you could add a new concept (something like `UniqueWhereNotNull`) to your application, with in implementation of IConceptDatabaseDefinition that creates the unique index as you have described.

It is also possible to create a custom concept that would modify the behavior of all Unique constraints in you application as you have described. All indexes in Rhetos already have a tag for extending them with similar options (SqlIndexMultipleDatabaseDefinition.Options2Tag). This implementation is not trivial. I might take some time to sketch the solution if you need it.

**Comment by marijok** [comment]
Tnx. Will go with 'UniqueWhereNotNull' for now until we r&d perfromance issues.

**Comment by bantolov** [comment]
One possible solution that is missing from my previous reply is to use low-level database concepts in DSL script to directly create this index in the database.
For example, for property *MyColumn* on entity *MyModule.MyEntity*:

```C
SqlObject IX_MyEntity_MyColumn_NotNull
    "CREATE UNIQUE NONCLUSTERED INDEX IX_MyEntity_MyColumn_NotNull
        ON MyModule.MyEntity(MyColumn)
        WHERE MyColumn IS NOT NULL"
    "DROP INDEX IX_MyEntity_MyColumn_NotNull
        ON MyModule.MyEntity"
{
    SqlDependsOn MyModule.MyEntity.MyColumn;
}
```

If you need to use this in more that one place, the preferred solution would be to create a custom DSL concept `UniqueWhereNotNull` as mentioned above that will generate an equivalent code.

**Comment by bantolov** [comment]
Besides the workarounds above, a possible solution is a new concept as described in #177.
