### ISSUE TITLE
rhetos and i18n

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#131]
Hi,

i have a following exception: [[[It is not allowed to enter %0 because the required property %1 is not set.|||Warehouse.Receipt|||Principal]]]

My messages.po file has following translation:

#. 1 occurrences.
msgid "It is not allowed to enter '%0' because the required property '%1' is not set."
msgstr "Nije dopušteno stvoriti primku iz pošiljke za koju nije postavljeno polje nalogodavac."

I can't seem to find an exact string which will match this exception. 
On the other hand, somehow this:

#. 1 occurrences.
msgid "You are not authorized for action '%0' on resource '%1', user '%2'."
msgstr "Nemate ovlasti za pristup, korisnik '%2'."

Works?

**Comment by bantolov** [comment]
Please check if the strings are identical. There seems to be an apostrophe in msgid, but not in the web response.

**Comment by ikudeljnj** [comment]
I've tried both cases. And as I've said, the other example works with an apostrophe.

**Comment by bantolov** [comment]
Have you tried modifying the encoding od the .po file (ansi, utf-8, utf-8 with bom)?
I'm not sure it's related to this problem, but I have seen some similar issues related to this file encoding.

**Comment by ikudeljnj** [comment]
The final answer that works is> 

#. 1 occurrences.
msgid "It is not allowed to enter %0 because the required property %1 is not set."
msgstr "Nije dopušteno stvoriti primku iz pošiljke za koju nije postavljeno polje nalogodavac."

I've mistakenly thought that " ' " is a added char, while it was actually a part of the message in previous example.
