### ISSUE TITLE
SqlUtility.BoolToString(bool b) returns incorrect value

### ISSUE THREAD

**Issue by ndtung449** [Rhetos/Rhetos#132]
**Describe the bug**
![image](https://user-images.githubusercontent.com/27561025/54195474-537cb680-44f1-11e9-9321-20d272c69c92.png)

**Expected behavior**
It should return "1" when b is true and "0" when b is false

**Comment by bantolov** [comment]
Thank you for reporting the bug! It will be fixed in the next release.

From what I can find in core packages, it seems to affect AutoCodeForEach when the grouping is defined by a Bool property.
