### ISSUE TITLE
Unique constraint enforced when removed and migration scripts inserts new data in same build

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#143]
**Describe the bug**
We have the following scenario. Let's say there's a table

Entity Status
{ 
  ShortString Code { Unique; Required; }
  ShortString Name{ Unique; Required; }
}

And we wrote a concept UniqueMultiple 'Code Name', which is a concept which makes records unique over two properties.

So we change the entity to

Entity Status
{ 
  ShortString Code {  Required; }
  ShortString Name{  Required; }
  UniqueMultiple 'Code Name';
}

And Write the migration script which inserts two records:

1. Code = '001', Name = 'Status A'
2. Code = '002', Name = 'Status A'

The build fails with Cannot insert duplicate key row in object 'MasterData.PositionStatus' with unique index 'IX_PositionStatus_Name'. The duplicate key value is (posiljka u najavi- distribucijsko skladiste).
The statement has been terminated.

I would prefer if the solution wasn't: Build it in steps :)

**Comment by bantolov** [comment]
This is a special case with data-migration scripts, I'll describe the workaround here.

When running DeployPackages.exe, the data-migration scripts are executed *before* the indexes (and other objects) are created or removed on the database. This is why a standard data-migration script will result with the database error `Cannot insert duplicate key row...`.

A possible workaround is to drop the unique index directly in the data-migration script,
before applying the data modifications to your table (before DataMigrationApplyMultiple). To do it safely, you will need to update Rhetos metadata in table `AppliedConcept`, to avoid any issues with future deployments.

Here is example of the modified data-migration script. The only difference from a standard script is the added block of code that handles `AppliedConcept` and `IX_Status_Name`.

```sql
/*DATAMIGRATION BC9C8DC3-CA64-47FF-8360-C0DEB41A9717*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Demo', 'Status';
EXEC Rhetos.DataMigrationUse 'Demo', 'Status', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Demo', 'Status', 'Code', 'nvarchar(256)';
EXEC Rhetos.DataMigrationUse 'Demo', 'Status', 'Name', 'nvarchar(256)';
GO

IF NOT EXISTS (SELECT * FROM _Demo.Status)
BEGIN
    INSERT INTO _Demo.Status (ID, Code, Name) SELECT NEWID(), '1', 'A';
    INSERT INTO _Demo.Status (ID, Code, Name) SELECT NEWID(), '2', 'A';
END

-- The following part is required before DataMigrationApplyMultiple to avoid the unique constraint error:
-- "Cannot insert duplicate key row in object 'Demo.Status' with unique index 'IX_Status_Name'. The duplicate key value is (A)."
IF EXISTS (SELECT * FROM Rhetos.AppliedConcept WHERE CreateQuery LIKE 'CREATE%INDEX% IX_Status_Name %')
BEGIN
    DROP INDEX IX_Status_Name ON Demo.Status;
    DELETE FROM Rhetos.AppliedConcept WHERE CreateQuery LIKE 'CREATE%INDEX% IX_Status_Name %';
END

EXEC Rhetos.DataMigrationApplyMultiple 'Demo', 'Status', 'ID, Code, Name';
```

Modifying the database objects in data-migration scripts can be risky if you are not fully aware of the context, so it should only be used in rare cases when there is no better workaround available.

**Comment by bantolov** [comment]
I have added this example to the [wiki article on data migration](https://github.com/Rhetos/Rhetos/wiki/Data-migration#database-constraint-blocking-the-data-migration).
