### ISSUE TITLE
What are my options if I wish to employ custom logging inside Rhetos?

### ISSUE THREAD

**Issue by Halky** [Rhetos/Rhetos#144]
If I wish to write custom logging inside Rhetos - like logging to file, database, or similar, what are my options?
As far as I'm aware there is a Logger class on Rhetos context (_executionContext.LogProvider.GetLogger) and it seems awful like standard NLog provider. However, I'm not sure could I use it freely or are there any restriction which should be honored especially in production environment. 

Common scenario where logging API could be used to have detailed custom logging inside Action or ComposableFilterBy concepts. 

I was unable to find any kind of guideline or manual regarding Rhetos Logging API.

**Comment by bantolov** [comment]
If you need those log entries to be (losely) connected to the business objects in the system, and the ability to read them inside the application, than the best choice is probably the existing Common.Log table.

If you need an external log that can be easily shipped to other systems (files, **Azure Application Insights** and similar), then use the LogProvider. As you noticed, LogProvider is a wrapper around NLog. You can define you custom event types (`context.LogProvider.GetLogger("my event type")`) and set the configuration in `Web.config` to define rules on when and where to send those events.
See the `nlog` section in your Rhetos server's *Web.config* file for some examples.
See the  NLog documentation for available options: <https://nlog-project.org/config/?tab=targets>
