### ISSUE TITLE
Options to suppress rollbacks on error

### ISSUE THREAD

**Issue by Halky** [Rhetos/Rhetos#146]
**Is your feature request related to a problem? Please describe.**
During development, sometimes it's very hard to find out the root cause of error when Rhetos rollbacks the whole state of database before error (exception) occurred. 

**Describe the solution you'd like**
Option to configure Rhetos so it doesn't rollback data when error occurs.

**Comment by bantolov** [comment]
There is a command-line switch for DeployPackages.exe that should help with this: `/ShortTransactions`
Please try it and check if it solves the issue.

It will change the transaction handling in DeployPackages to commit after each modification in the database structure. Without this switch, the deployment is done in few transactions (one for each phase, and some more for situations when the commit is necessary).

The DeployPackages switches are not yet documented on wiki. There is just a brief description available in the utility:

```
C:\My Projects\Rhetos\Source\Rhetos\bin>DeployPackages.exe /?

Command-line arguments:
/StartPaused   Use for debugging with Visual Studio (Attach to Process).
/Debug         Generates unoptimized dlls (ServerDom.*.dll, e.g.) for debugging.
/NoPause       Don't pause on error. Use this switch for build automation.
/IgnoreDependencies  Allow installing incompatible versions of Rhetos packages.
/ShortTransactions  Commit transaction after creating or dropping each database object.
/DatabaseOnly  Keep old plugins and files in bin\Generated.
/SkipRecompute  Use this if you want to skip all computed data.
```

**Comment by Halky** [comment]
Works lika a charm.
Behavior behind ShortTransactions is what I was looking for.
