### ISSUE TITLE
DeployPackages - information where the deployment error originated in DSL files

### ISSUE THREAD

**Issue by Halky** [Rhetos/Rhetos#148]
**Is your feature request related to a problem? Please describe.**
Sometimes, when Rhetos deployment process aborts it's almost impossible to know origin of error in DSL scripts.
At the moment Rhetos (DeployPackages.exe) informs you where the error occurred in the generated .cs files
E.g.
```
DslSyntaxException: Unrecognized concept ...
after: "...."
before: "..."
```

**Describe the solution you'd like**
It would be nice if Rhetos could also tell where the error occurred in DSL files.
E.g. 
```
DslSyntaxException: Unrecognized concept ...
after: "...."
before: "..."
maps to: C:\Projects\RhetosScripts\DslScripts\Car.rhe line 200
```

**Comment by bantolov** [comment]
What version of Rhetos are you currently using?
I tried changing "Entity" to "Entityy" and got an error with file and line number:

```
DslSyntaxException: Unrecognized concept keyword 'Entityy'. At line 3, column 5, file 'C:\...
\CommonConceptsTest\DslScripts\Action.rhe',
after: "Module TestAction {",
before: "Entityy ToInsert { LongString Name; } Action InsertAndThrowExceptio...".
```

**Comment by Halky** [comment]
I must admit, until know, I simply did not see this part of an error. Oversight on my end.

**Comment by bantolov** [comment]
I think the misunderstand might be caused by an unintuitive error format. I have created a new feature request to match the C# error output format: #157
