### ISSUE TITLE
Using nuget packages

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#153]
I need a zip library and found one on nuget:
https://www.nuget.org/packages/DotNetZip/

I've added it to RhetosPackages.config:   <package id="DotNetZip"/>

And i can use it in playground project like this:
                using (Ionic.Zip.ZipFile zip = new Ionic.Zip.ZipFile())
                {

                }

But when i put it in DSL script it says: FrameworkException: 2 errors while compiling 'ServerDom.Repositories.cs':The type or namespace name 'Ionic' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ibarban** [comment]
Hi,

The problem is that Rhetos does not include additional dll-s during compilation time if you do not tell it to do so. You can achieve this by using the ExternalReferenceInfo concept and specifying the assembly name that you want to include during compilation.

**Comment by ikudeljnj** [comment]
Im having a hard time guessing what i need to write in that string?

pon, 20. svi 2019. u 12:01 ibarbancic <notifications@github.com> napisao je:

**Comment by ibarban** [comment]
I have just edited the comment so that includes an example :)

**Comment by ikudeljnj** [comment]
I've tried that, and it says:
Metadata file 'Ionic.Zip.ZipFile, Ionic' could not be found
or
Metadata file 'Ionic.Zip, Ionic' could not be found

**Comment by ibarban** [comment]
I wrote the example wrong. It should be
```
Module Module1
{
    ExternalReference 'Ionic.Zip.ZipFile, Ionic.Zip'
}
```
because the assembly name is not Ionic but Ionic.Zip

**Comment by ikudeljnj** [comment]
This one seems to work, only combo i haven't tried -.-. Thanks!
