### ISSUE TITLE
Unit testing - how to test single ItemFilter 

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#161]
Hello!

Let's say we have an entity 

Entity Package
{
  Integer Width;
  Integer Height;
  Integer Length;
}

And we have two ItemFilters / InvalidData declarations.

ItemFilter PackageWidthLargerThan10 ' item => item.Width > 10';
InvalidData PackageWidthLargerThan10;

ItemFilter PackageHeightSmallerThan10 ' item => item.Height < 10';
InvalidData PackageHeightSmallerThan10;

Now, we want to unit test each of these validations. In my experience so far, item filters will generate code in sequence in which they are declared, so in order to pass the test you need to set both Widht > 10 and Height < 10.

BUT, let's say i want to test only the second one, Height < 10. How can i make it so that i don't have to set the Width property > 10 and still have a successfull test?

I hope I've explained myself well, but if you need additional clarification, let me know.

Regards,
Ivan

**Comment by ibarban** [comment]
Hi,

You should not depend on the premise that Rhetos will generate the code in the order in which the concepts are declared.

The fact that you can just check one validation is a drawback of the InvalidData concept.

One way you can bypass this is by testing just the ItemFilter and not the validation itself.
For example you can do something like this
```
Assert.IsTrue(repository.ModuleName.Package.Filter(repository.ModuleName.Package.Query().Where(x => x.ID == itemID), new ModuleName.PackageHeightSmallerThan10()).Any());
```
The above code will check if there are any invalid data, that is, it will just use the filter generated by ItemFilter PackageHeightSmallerThan10 on all the data.

**Comment by ikudeljnj** [comment]
That's the answer i was hoping for, thanks.
