### ISSUE TITLE
How to create a "base enitty"?

### ISSUE THREAD

**Issue by vinkoSego** [Rhetos/Rhetos#166]
Hi,

Is there a way to create a "base entity" which would contain some properties (like code, createdTime, logging ...) contained in almost every entity through the project, so we don't have to write them manually?

Regards,
Vinko

**Comment by bantolov** [comment]
If you only need some properties added to multiple entities (or similar objects), you can use a very simple helper concept **AllPropertiesFrom**.

In the following example, the properties Code and Name are "copied" from BasicPropertiesTemplate to entities BookType and Warehouse.

```C
DataStructure BasicPropertiesTemplate
{
    Integer Code;
    ShortString Name;
}

Entity BookType
{
    AllPropertiesFrom Demo.BasicPropertiesTemplate; // Adds the two properties.
}

Entity Warehouse
{
    AllPropertiesFrom Demo.BasicPropertiesTemplate; // Adds the two properties.
    Integer Capacity; // Additional property.
}
```

Note that AllPropertiesFrom does not copy any other feature besides the simple list of properties.

If you need to add additional features to multiple entities (Required, AutoCode, CreatedAt, Logging, ...), the most flexible way is to [write a custom macro concept](https://github.com/Rhetos/Rhetos/wiki/Rhetos-concept-development#how-to-write-a-macro-concept).

In the following example, a custom concept "Codebook" is implemented to generate some repeating features on multiple entities.

```C
// Original code:

Entity BookType
{
    ShortString Code { AutoCode; }
    ShortString Name { Required; }
    Logging;
}

Entity Warehouse
{
    ShortString Code { AutoCode; }
    ShortString Name { Required; }
    Integer Capacity;
    Logging;
}

// After implementing custom concept "Codebook":

Entity BookType
{
    Codebook;
}

Entity Warehouse
{
    Codebook;
    Integer Capacity;
}
```
