### ISSUE TITLE
Why does unauthorized return 400, bad request

### ISSUE THREAD

**Issue by ikudeljnj** [Rhetos/Rhetos#182]
Hi,

so, i'm trying to detect if the user is authorized to perform certain action. In this case, to actually log in into system and get some basic data. 

So i've deleted all the roles my user has, and deleted the user from the database. The trouble is i always get HTTP response with code 400, which is only distinguishable from other errors by user message on the frontend. 

Do you have a suggestion how to handle this situation?

Regards,
Ivan

**Comment by bantolov** [comment]
This is a known issue we need to solve, reported in #120. I will close this one as a duplicate.

A possible workaround is to detect unauthorized requests by checking the UserMessage and SystemMessage value in the web response.

If most web application that we have written, there was no need to "catch" this kind of error in the application. Instead we have just used the standard error handling that shows the UserMessage to the end user, usually translated to a more user-friendly message by a localization plugin such as [turquoiseowl/i18n](https://github.com/turquoiseowl/i18n).
