### ISSUE TITLE
GenericFilter "notequal" and "notequals" translates to Expression.Equal

### ISSUE THREAD

**Issue by hmilas** [Rhetos/Rhetos#225]
**Describe the bug**
If you have generic filter with operator "notequal" or "notequals" and Guid type value, Rhetos builds wrong expression with Expression.Equal, instead of Expression.NotEqual

Also, I don't see a test with this specific case (also looked in CommonConcepts.Test project)

**To Reproduce**
For example, is you have REST like this:
http://localhost/centrix2rhetos/rest/Ustrojstvo/ZaposlenikBrowse/?skip=0&top=21&sort=ActiveSince desc&genericfilter=[{"Property":"Active","Operation":"equal","Value":true},{"Property":"PripadaID","Operation":"notequal","Value":"e5c95a6b-732f-4527-a7e3-eedd80787aed"}]

generated SQL query would be (non related truncated):
'.. WHERE [Filter1].[PripadaID] = @p__linq__0 ..'

The bug is introduced in latest 3.0.0 release, commit:
https://github.com/Rhetos/Rhetos/commit/9f24f6d724851ee1cbbbc3ae596666c9a5a9d1bd#diff-fa9ad020d5711f4f911a528a829e3ebcR188

**Error message**
No error message, just wrong behaviour.

**Expected behavior**
"notequal" operator should translate to Expression.NotEqual

**Comment by bantolov** [comment]
Closed in #226
