### ISSUE TITLE
AspNetFormsAuth: Sending password reset token by email

### ISSUE THREAD

**Issue by Rhetos** [Rhetos/Rhetos#31]
The existing **GeneratePasswordResetToken** method cannot allow **anonymous** user access and cannot easily be used in **forgot-password** scenario. Another web method is needed for anonymous user (who forgot the password) to send the token to previously registered email address. The same issue occurs whether a user is accessing the Rhetos server directly or using a web application that impersonates the user.

**Comment by bantolov** [comment]
Sample implementation in https://github.com/Rhetos/SimpleSPRTEmail.
