### ISSUE TITLE
Row permissions inheriting from circular reference

### ISSUE THREAD

**Issue by davorpr1** [Rhetos/Rhetos#35]
When exists self reference on entities for which row permissions are to be applied, error occurs when reference is included in checking row permissions.
Workaround is to use extension (SqlQueryable or similar) in which identifier for self reference (or its properties) is declared as value type (Guid).

**Comment by bantolov** [comment]
Development considerations:
* We should review AutoInheritRowPermissionsMacro to see if there is a clean and reliable way to remove circular dependencies. If not, the simplest thing we can change it to ignore a self-reference when automatically inheriting row permissions; it will solve the case above without introducing new risks.
