### ISSUE TITLE
Admin and prototyping GUI

### ISSUE THREAD

**Issue by bantolov** [Rhetos/Rhetos#38]
Generated or generic GUI that allows CRUD operations on all data structures.

The GUI is intended for rapid application prototyping during development, and administration during production. It should use standard Rhetos permissions, so that any user can access it without security risks.

It can be improved to support other common features: executing action, downloading report, master-detail entities, recomputing persisted data, etc.

**Comment by bantolov** [comment]
The solution for this project is **already successfully developed**, but it's not published yet.

Some work has yet to be done on the project to verify if any of the following issues are still open, and solve them if needed:

* Move the existing repository to <https://github.com/Rhetos/AdminGui>.
* Develop automated tests.
* Check if the plugin supports Windows authentication. We should remove from the plugin any code that handles the authentication process or is specific to authentication options.
* Improve error handling (for example, if the user does not have permissions for a request, the error response message that is received from the server is not displayed).
* Remove all binaries from the repository, use NuGet where needed.

**Comment by ngoquoc** [comment]
Hi, I think more explanations are necessary for this point:
> Check if the plugin supports Windows authentication. We should remove from the plugin any code that handles the authentication process or is specific to authentication options.

I assume that it implies 2 things:
**1. Make sure the plugin support Windows authentication, and only Windows users can access the AdminGUI.** 
If that's correct, what's the usage of this plugin in the case that Rhetos server is deployed to a PaaS (e.g. Azure web app service)? Maybe the ideas in point 2 can resolve this issue.
**2. Remove specific authentication implementations from the plugin, or in the other words, make it authentication-mechanism-agnostic.** 
I'm wondering if it's possible to extend this plugins by developing plug-able authentication implementations. For example, we can have AdminGUI that only supports Windows authentication, then we can install additional plugin, let's say AdminGUI.AspNetFormsAuthentication to enable AspNet Forms authentication mechanism.

**Comment by bantolov** [comment]
@ngoquoc 
My original statement "Check if the plugin supports Windows authentication" is misleading. Your option 2 is correct. Since Rhetos application has can work with different authentication mechanisms (and new authentication plugins can be developed), the simplest and most powerful solution for now is to make AdminGui completely agnostic to the authentication mechanism. We should test if it current works with both windows and forms [authentication options](https://github.com/Rhetos/Rhetos/wiki/User-authentication-and-authorization).

It is a good idea to allow for AdminGui extension, but this feature could be postponed. For example, when using [forms authentication](https://github.com/Rhetos/AspNetFormsAuth), the Rhetos homepage already contains some very simple forms for logging in. So the AdminGui plugin does not need to handle this process at all.

**Comment by nguyenlamlll** [comment]
Hi @bantolov, there is one concern regarding this point that I think we should clarify
> Develop automated tests.

On which level are these tests will be? Unit, integration, or system level, or end-2-end UI tests against the UI generated by the plugin?

Should CI processes like health check/build check/PR check/etc. be included as well? Personally, I think we should 😄. Prolly I recommend TravisCI or Azure Pipelines. 

Thanks.

**Comment by bantolov** [comment]
Good question. I'd like to keep it is as simple as possible for the first release. A smoke test that checks if the web page is loaded could be enough for now, just to verify if anything is working at all. Perhaps using Selenium just to check if the web page loads without errors and contains at lest one entity name?

TravisCI integration would be great, but I don't know how complicated it would be to set it up (for example, deployment of a live Rhetos server could be a prerequisite).

To help with automated testing, we might simplify the build process described in README.md. For example, check out the "Build" and "Installation" chapters in [Readme.md](https://github.com/Rhetos/RestGenerator/blob/master/Readme.md#build) for the RestGenerator plugin.

**Comment by bantolov** [comment]
Closing this issue because of the development and planning is moved to the repository <https://github.com/Rhetos/AdminGui>.
Please continue the discussion and feature requests in the [issues list](https://github.com/Rhetos/AdminGui/issues) at AdminGui.
