### ISSUE TITLE
Can I run rhetos dsl at runtime?

### ISSUE THREAD

**Issue by furesoft** [Rhetos/Rhetos#450]
Is it possible to run rhetos dsl at runtime as script language?

**Comment by bantolov** [comment]
It cannot be used as a scripting language. It is designed to work as a compiler: During development, at build-time, Rhetos parses DSL scripts and generates C# code, the database structure (SQL scripts) and other assets.

The DSL model (from the parsed DSL scripts) is read-only at run-time.
