### ISSUE TITLE
Data migration script is not always updating data when database uses case insensitive collation

### ISSUE THREAD

**Issue by dkocis6** [Rhetos/Rhetos#459]
**Describe the bug**
Data migration script is not updating data in a column when database uses case insensitive collation and old and new value differ only in letter casing, e.g. when using UPPER function.
This happens because stored procedure Rhetos.DataMigrationApplyMultiple checks which rows it has to update based on not equal operator (original.ColumnName <> migration.ColumnName).

**To Reproduce**
Using [bookstore](https://github.com/Rhetos/Bookstore) demo application as an example, deploy rhetos on a database that uses one of the case insensitive collations and then insert a new record in Bookstore.Topic table:
```c
INSERT INTO Bookstore.Topic (ID, Name, Code)
VALUES (NEWID(), 'topic1', '01')
```
Then create data migration script:
```c
/*DATAMIGRATION C3177DBC-82ED-4BAD-B013-74E18CA1639E*/ -- Change the script's code only if it needs to be executed again.

-- The following lines are generated by: EXEC Rhetos.HelpDataMigration 'Bookstore', 'Topic';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Topic', 'ID', 'uniqueidentifier';
EXEC Rhetos.DataMigrationUse 'Bookstore', 'Topic', 'Name', 'nvarchar(256)';
GO

UPDATE _Bookstore.Topic
SET Name = UPPER(Name)

EXEC Rhetos.DataMigrationApplyMultiple 'Bookstore', 'Topic', 'ID, Name';
```

**Expected behavior**
Data migration script should update data in a column when old and new value differ only in letter casing even if database uses case insensitive collation.

**Comment by bantolov** [comment]
Solved by https://github.com/kfranic1/Rhetos/commit/228ab345e28a0eff0a1d9f4f06dbdd55c2432cf6
