### ISSUE TITLE
Implement a CLI tool to control all Rhetos' processes

### ISSUE THREAD

**Issue by nguyenlamlll** [Rhetos/Rhetos#47]
Hi, I am not sure if this is already on the roadmap or not but here goes. I think Rhetos needs a **centralized** command line tool to execute at least all the common works one user may do when he uses Rhetos. Right now, the scripts and the configurations are so discrete and scattered all around (well, at least from my viewpoint). For a reference/example, take a look here at [dotnet CLI tool](https://docs.microsoft.com/en-us/dotnet/core/tools/?tabs=netcore2x). Maybe it's an `rhetos.exe` to be downloaded. Then, we add it to `$PATH` and excute the commands in cmd or Powershell to help with the development using Rhetos. 

Haven't thought thoroughly but here are a few example commands:

- `rhetos new [--version]`: Create a new template project with Rhetos binaries and a sample Nuget package with one or two .rhe scripts.
- `rhetos config view`: A command to see all configurations of the current project at the path (We may need to discuss a way to detect a Rhetos project). The configurations can be database connections, and used packages. There can be some switches to extend this command as well. For example, `rhetos config view <package_name>` to view configurations of a specific package, or `rhetos config view all` for all packages found within the project.
- `rhetos config add <package_name> <package_to_be_added>`: This command adds a new dependency to a package. This one can cover the actions needed in `RhetosPackages.config` and `RhetosPackageSources.config`. Should also go with `rhetos config modify` and `rhetos config remove`, etc.
- `rhetos run`: Apply all the latest changes of the current project and start a new web server at a random port (quite similar to the way `dotnet run` or `npm start` behaves).
- ...

**Comment by nguyenlamlll** [comment]
From my viewpoint, I see Rhetos aims to be a standalone framework/library (as React). Therefore, I prefer a standalone CLI tool.

**Comment by VladimirZD** [comment]
Hi, we are working on this, i hope till end of next week we will upload first (beta) version of CLI.
In this version we will implement  rhetos new command.

**Comment by ngoquoc** [comment]
That's a great news. I guess it's going to be maintained in other repository. Do you plan to make it open source?

**Comment by VladimirZD** [comment]
It will be opensource, and we hope there will be a lot of contribution :)  For repository i am not sure but i think it will be diferent repo like RestGenerator or I18NFormatter

**Comment by bantolov** [comment]
A new repository is created for the CLI tool at <https://github.com/Rhetos/RhetosCli>, and the first version of the tool is already available there (thanks @VladimirZD).
I'm closing this issue, please continue the discussion and feature requests in the [issues list](https://github.com/Rhetos/RhetosCli/issues) at RhetosCli.
