### ISSUE TITLE
Better IDE with seamless C# code development

### ISSUE THREAD

**Issue by bantolov** [Rhetos/Rhetos#49]
Motivation:

* Significantly simplify the development and debugging of C# code in Rhetos applications.
* Improve developer’s learning speed with IntelliSense.
* Most important project in the list, but is not yet ready for development.

Scope:

* Implement an extension for VS Code for Rhetos application development (with code snippets, linting, build integration, integrated error reporting and code formatting.
* Better syntax highlighting and IntelliSense support for C# and SQL code.
* Writing C# code snippet with full user-experience of IDE for C# projects, without copy-pasting or using external projects. Using C# compiler in VS Code for Rhetos C# snippets.
* Build and deployment integrated into VS Code.

Next steps:

* Research and brainstorming.
* Research VS Code T4 implementation; its technology is probably very close to what we need.
* Research Language Server Protocol

Notes:

* The existing plugin (https://github.com/Rhetos/RhetosVSCode) contains only syntax highlighting.

**Comment by ngoquoc** [comment]
This can be a trivial task once VSCode team resolves this issue: Microsoft/vscode#1751.
Vote up for it :)

**Comment by bantolov** [comment]
Related to this topic, there is currently a research and prototyping project in progress on <https://github.com/ibarban/rhetos-lsp>: VSCode plugin for Rhetos that uses Language Server Protocol.

**Comment by minkir014** [comment]
I think these all are supported now with language server of Rhetos. It's very beautiful

**Comment by bantolov** [comment]
Rhetos core team is currently working on this project. Our vision is to provide a more natural development workflow with less emphasis on Rhetos.

1. New Rhetos application should be created directly in Visual Studio by creating a new web application.
2. Rhetos framework can be included in the application simply by adding Rhetos NuGet package. This will allow compiling DSL scripts as part of the application.
3. Build and run in Visual Studio should automatically include compilation of the DSL scripts.
4. Developer can develop the application directly (for example by adding new web services and methods in C#) or by writing code in DSL scripts and generating services by Rhetos. Both methods should work together on the same application at the same time.

We hope to change the developer's mindset to look at the Rhetos application not as a special type of application in a world of it's own, but more like a standard web application that includes DSL scripts.

We will achieve this by reducing breadth of Rhetos framework responsibilities. It should be focused on generating C#/database/other code from DSL scripts. It should be more technology-independent regarding web stack, user authentication and similar common issues solved by other .NET tools and libraries.

The first results will be published in next major release (Rhetos 4.0). The first release will probably support only WCF applications, but internally it should not depend on application's technology. This will allow us eventually to use it on other types of applications starting from Console applications to ASP.NET Core in future releases.

**Comment by bantolov** [comment]
The planed changes from this issue are released with Rhetos v4.0.0, so I am closing this issue.

See the [Release notes](https://github.com/Rhetos/Rhetos/blob/master/ChangeLog.md#400-2020-05-14) for details on new features and migration of existing applications.
Here is the summary:

> Major change in this release is **simpler development and build process** for applications on Rhetos framework:
> 1. A new Rhetos application is created as a regular application in Visual Studio, with added Rhetos.MSBuild NuGet package. Currently only WCF applications are supported, but we are planning to support any application type in future releases.
> 2. Custom C# code is compiled together with DSL scripts, as a part of build in Visual Studio (MSBuild). This will make build process simpler, without a need to manage separate “Runtime” libraries.
> 3. Rhetos **DSL IntelliSense for Visual Studio** provides syntax highlighting, context-sensitive autocompletion, concept description with parameters and real-time syntax errors. See installation instructions and features at Visual Studio Marketplace.
> 
> **Upgrading existing applications** to Rhetos 4.0:
> 1. Even if you keep using the existing development process with DeployPackages, you will need to follow the migration instructions under the **“Breaking changes”** section below.
> 2. Additionally, for migrating an existing application to new development process with Rhetos CLI, see Migrating from DeployPackages to Rhetos CLI.


We have some new ideas for future releases that might further simplify the development process. We will open new issues for these topics.

* Creating custom repository methods for Rhetos actions, filters and similar concepts.
  This will help developers by supplying input and output types for each method, and further reducing lines of C# code in DSL scripts.
* Support for using Rhetos framework on any project type, including ASP.NET Core.
