### ISSUE TITLE
Apply new concept keyword to more than one existing concepts

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#56]
Hello,

We built a new concept that sits on top of DataStructure.

```C#
    //defines this class as a plugin for rhetos
    [Export(typeof(IConceptInfo))]
    //defines the concept keyword in dsl scripts
    [ConceptKeyword("Inherits")]
    public class InheritsInfo : IConceptInfo
    {
        [ConceptKey]
        public DataStructureInfo DataStructure { get; set; }

        public string DataStructureName { get; set; }
    }
```

How can we apply the same concpet to Compute?

**Comment by bantolov** [comment]
The *Computed* concept is a derivation of the DataStructure, so this concept should automatically be applicable to it. Please provide more details on the error that occurs.

**Comment by marijok** [comment]
When adding "Inherits" to Computed in .rhe the error is:

C:\Projects\Knjizara\RhetosServer\bin>DeployPackages.exe
[Trace] DeployPackages: Moving old generated files to cache.
[Trace] DeployPackages: Getting packages.
[Trace] DeployPackages: Reading package from cache 'Rhetos.CommonConcepts.2.7.0'.
[Trace] DeployPackages: Reading package from cache 'Rhetos.RestGenerator.2.5.0'.
[Trace] DeployPackages: Loading plugins.
[Trace] DeployPackages: SQL connection: DataSource=.\SQLEXPRESS, InitialCatalog=Knjizara
[Trace] DeployPackages: Preparing Rhetos database.
[Trace] DeployPackages: Parsing DSL scripts.
[Trace] DeployPackages: Application model has 974 statements.
[Trace] DeployPackages: Compiling DOM assembly.
[Error] CodeGenerator: Rhetos.FrameworkException: Generated script does not contain tag "/*DataStructureInfo ClassInterace NestedJson.ParentDTOByID*/". Error occurred while inserting code " : NestedJson.Parent".
   at Rhetos.Compiler.CodeBuilder.CheckTag(String code, String tag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 109
   at Rhetos.Compiler.CodeBuilder.InsertCode(String code, String tag, Boolean insertAfterTag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 74
   at Rhetos.Compiler.CodeBuilder.InsertCode(String code, String tag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 69
   at KnjizaraRhetosExtensions.InheritsCodeGenerator.GenerateCode(IConceptInfo conceptInfo, ICodeBuilder codeBuilder) in C:\Projects\Knjizara\KnjizaraRhetosExtensions\Inherits.cs:line 46
   at Rhetos.Compiler.CodeGenerator.ExecutePlugins[TPlugin](IPluginsContainer`1 plugins, String tagOpen, String tagClose, IConceptCodeGenerator initialCodeGenerator) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeGenerator.cs:line 60
Info:
[Error] CodeGenerator: Part of the source code that was generated before the exception was thrown is written in the trace log.
[Error] DeployPackages: Rhetos.FrameworkException: Generated script does not contain tag "/*DataStructureInfo ClassInterace NestedJson.ParentDTOByID*/". Error occurred while inserting code " : NestedJson.Parent".
   at Rhetos.Compiler.CodeBuilder.CheckTag(String code, String tag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 109
   at Rhetos.Compiler.CodeBuilder.InsertCode(String code, String tag, Boolean insertAfterTag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 74
   at Rhetos.Compiler.CodeBuilder.InsertCode(String code, String tag) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeBuilder.cs:line 69
   at KnjizaraRhetosExtensions.InheritsCodeGenerator.GenerateCode(IConceptInfo conceptInfo, ICodeBuilder codeBuilder) in C:\Projects\Knjizara\KnjizaraRhetosExtensions\Inherits.cs:line 46
   at Rhetos.Compiler.CodeGenerator.ExecutePlugins[TPlugin](IPluginsContainer`1 plugins, String tagOpen, String tagClose, IConceptCodeGenerator initialCodeGenerator) in C:\My Projects\Rhetos\Source\Rhetos.Compiler\CodeGenerator.cs:line 67
   at Rhetos.Dom.DomGenerator.GenerateObjectModel() in C:\My Projects\Rhetos\Source\Rhetos.Dom\DomGenerator.cs:line 77
   at Rhetos.Dom.DomGenerator.get_Assemblies() in C:\My Projects\Rhetos\Source\Rhetos.Dom\DomGenerator.cs:line 70
   at Rhetos.Dom.DomainObjectModelExtensions.GetTypes(IDomainObjectModel dom) in C:\My Projects\Rhetos\Source\Rhetos.Dom.Interfaces\IDomainObjectModel.cs:line 51
   at Rhetos.Deployment.ApplicationGenerator.ExecuteGenerators(Boolean deployDatabaseOnly) in C:\My Projects\Rhetos\Source\Rhetos.Deployment\ApplicationGenerator.cs:line 87
   at DeployPackages.Program.GenerateApplication(ILogger logger, Arguments arguments) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 183
   at DeployPackages.Program.Main(String[] args) in C:\My Projects\Rhetos\Source\DeployPackages\Program.cs:line 69
Info:

=== ERROR SUMMARY ===
FrameworkException: Generated script does not contain tag "/*DataStructureInfo ClassInterace NestedJson.ParentDTOByID*/". Error occurred while inserting code " : NestedJson.Parent".

See DeployPackages.log for more information on error. Enable TraceLog in DeployPackages.exe.config for even more details.
Press any key to continue . . .  (use /NoPause switch to avoid pause on error)


C# code:
`
using Rhetos.Compiler;
using Rhetos.Dom.DefaultConcepts;
using Rhetos.Dsl;
using Rhetos.Dsl.DefaultConcepts;
using Rhetos.Extensibility;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KnjizaraRhetosExtensions
{
    //defines this class as a plugin for rhetos
    [Export(typeof(IConceptInfo))]
    //defines the concept keyword in dsl scripts
    [ConceptKeyword("Inherits")]
    public class InheritsInfo : IConceptInfo
    {
        [ConceptKey]
        public DataStructureInfo DataStructure { get; set; }

        // can't use this because then it does not work with DataStructure only
        //[ConceptKey]
        //public ComputedInfo Computed { get; set; }

        public string DataStructureName { get; set; }
    }

    //defines this class as a plugin for rhetos
    [Export(typeof(IConceptCodeGenerator))]
    [ExportMetadata(MefProvider.Implements, typeof(InheritsInfo))]    
    public class InheritsCodeGenerator : IConceptCodeGenerator
    {
        public void GenerateCode(IConceptInfo conceptInfo, ICodeBuilder codeBuilder)
        {
            var info = (InheritsInfo)conceptInfo;            

            //codeBuilder.InsertCode("[DataMember]", PropertyHelper.AttributeTag, info);

            var codeSnippet = string.Format(" : {0}",info.DataStructureName);

            if (info.DataStructure != null)
            {
                codeBuilder.InsertCode(
                codeSnippet,
                //inserts code after Initialization comment in repository class (look for /*DataStructureInfo WritableOrm Initialization ModuleName.EntityName*/ in generated repository class

                DataStructureCodeGenerator.InterfaceTag.Evaluate(
                    //needs this so we know in what repository to put the code snippet
                    info.DataStructure));
            }

            //if (info.Computed != null)
            //{
            //    codeBuilder.InsertCode(
            //    codeSnippet,
            //    //inserts code after Initialization comment in repository class (look for /*DataStructureInfo WritableOrm Initialization ModuleName.EntityName*/ in generated repository class

            //    DataStructureCodeGenerator.InterfaceTag.Evaluate(
            //        //needs this so we know in what repository to put the code snippet
            //        info.Computed));
            //}

        }
    }
}
`

**Comment by marijok** [comment]
Tnx, now I have a new problem. `Computed NestedJson.ParentDTO` creates a class  `public class ParentDTO : EntityBase<NestedJson.ParentDTO>` and when we apply our `Inherits` concept the result is  `public class ParentDTO : EntityBase<NestedJson.ParentDTO>, NestedJson.Parent` which does not compile because a class can't have many base classes. Any ideas how to add `NestedJson.Parent` as base class of `NestedJson.ParentDTO`?

**Comment by damirdean** [comment]
Please, provide part of dsl source that creates the problem, so I can get better overview of the problem.

**Comment by marijok** [comment]
The problem is in the generated `NestedJson.ParentDTO` class:
```
Module NestedJson
{   
    DataStructure SubChildDTO
    {
        ShortString SubChildNaziv;
    }

    Entity Child
    {
        ShortString ChildNaziv;
        Reference Parent;
    }

    DataStructure ChildDTO
    {
        Inherits 'NestedJson.Child';        
        Object SubChildren 'NestedJson.SubChildDTO[]';        
    }

    Entity Parent
    {
        ShortString ParentNaziv;
    }
    
    Computed ParentDTO '(repository) => this.Load(new ParentID { ID = new Guid("") }).ToArray();'
    {
        Inherits 'NestedJson.Parent';
        Object Children 'NestedJson.ChildDTO[]';
        
        FilterBy ParentID '(repository, parameter) =>
        {
            var parent = _domRepository.NestedJson.Parent.Query()
                .Where(x => x.ID == parameter.ID)
                .SingleOrDefault();

            if(parent == null)
            {
                throw new Rhetos.UserException(String.Format("Parent with ID: {0} not found", parameter.ID));
            }

            var parentDTO = new NestedJson.ParentDTO { ID = parent.ID, ParentNaziv = parent.ParentNaziv };

            parentDTO.Children = _domRepository.NestedJson.Child.Query()
                    .Where(x => x.ParentID == parameter.ID) 
                    .Select(x => new NestedJson.ChildDTO {
                        ID = x.ID,
                        ChildNaziv = x.ChildNaziv })
                    .ToArray();

            return new NestedJson.ParentDTO[] { new NestedJson.ParentDTO { Parent = parentDTO } };
        }';
    }

    Parameter ParentID
    {
        Guid ID;
    }
}
```
Inerits concept:
```
using Rhetos.Compiler;
using Rhetos.Dom.DefaultConcepts;
using Rhetos.Dsl;
using Rhetos.Dsl.DefaultConcepts;
using Rhetos.Extensibility;
using System;
using System.Collections.Generic;
using System.ComponentModel.Composition;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KnjizaraRhetosExtensions
{
    //defines this class as a plugin for rhetos
    [Export(typeof(IConceptInfo))]
    //defines the concept keyword in dsl scripts
    [ConceptKeyword("Inherits")]
    public class InheritsInfo : IConceptInfo
    {
        [ConceptKey]
        public DataStructureInfo DataStructure { get; set; }
                
        public string DataStructureName { get; set; }
    }

    
    //defines this class as a plugin for rhetos
    [Export(typeof(IConceptCodeGenerator))]
    [ExportMetadata(MefProvider.Implements, typeof(InheritsInfo))]    
    public class InheritsCodeGenerator : IConceptCodeGenerator
    {
        public static void AddInterfaceAndReference(ICodeBuilder codeBuilder, string typeName, Type type, DataStructureInfo dataStructureInfo)
        {
            codeBuilder.InsertCode(typeName, DataStructureCodeGenerator.InterfaceTag, dataStructureInfo);
        }

        public void GenerateCode(IConceptInfo conceptInfo, ICodeBuilder codeBuilder)
        {
            var info = (InheritsInfo)conceptInfo;

            var codeSnippet = string.Format("{0}", info.DataStructureName);

            codeBuilder.InsertCode(
                    codeSnippet,
                    DataStructureCodeGenerator.InterfaceTag,
                    info.DataStructure);
            
        }
    }
}
```

**Comment by damirdean** [comment]
As you allready found out, your Inherits concept won't work. The thing is CommonConcepts architecture of data structures simply doesn't allow inheritance for number of reasons. Luckily, simmilar concept is allready implemented -  [Polymorphic concept](https://github.com/Rhetos/Rhetos/wiki/Polymorphic-concept) . It has all the features and more of what you try to implement with Inherits concept.

**Comment by bantolov** [comment]
As @damirdean said, I don't think there is a reasonable way to add inheritance to the class of the Computed data structure.
The simplest approach I can think of right now is to separate DTO from the reader: create ParentDTO as a simple DataStructure (with Inherits), and then use a separate `Computed ParentReader` to read the data, where ParentDTO is a property (`Object ParentDTO 'NestedJson.ParentDTO';`).

I hope most of these issues will be gone soon when we implement GraphQL (planned issue #50) for simple creation of DTOs or view-models on the server side.

**Comment by marijok** [comment]
Ok, tnx, that will work.
