### ISSUE TITLE
using statement in generated .cs files

### ISSUE THREAD

**Issue by marijok** [Rhetos/Rhetos#70]
We would like to use a third party assembly in RestService.cs generated code. Is there a way to add a using statement in a generated RestService.cs file?

**Comment by ibarban** [comment]
If you are adding some code snippet that has a dependency on another assembly the ICodeBuilder has some methods to add the dependencies of that code snippet.
For example if your code snippet depends on Newtonsoft.Json.JsonConvert you can use codeBuilder.AddReferencesFromDependency(typeof(Newtonsoft.Json.JsonConvert)) to add the reference to the assembly that has the Newtonsoft.Json.JsonConvert type defined.

**Comment by marijok** [comment]
Ok, but when you use Newtonsoft.Json.JsonConvert in c# code, you have to write full class name with namespace. There is no way to add `using Newtonsoft.Json;` on top so you can write JsonConvert.... in c# without "Newtonsoft.Json"?

**Comment by ibarban** [comment]
Yes, you are right, it appears that RestService.cs does not have any tag that would be used to add the using directive. The only option for now is to use the full type name.

**Comment by bantolov** [comment]
This is a valid improvement. We are adding it to backlog.
