### ISSUE TITLE
Unit testing for Rhetos plugins

### ISSUE THREAD

**Issue by ngoquoc** [Rhetos/Rhetos#74]
In our project which is built on top of Rhetos, there is a huge need of having unit tests that cover the crucial business logic/rules. Let's say we have business rules spread over 3 major places inside our application:

1. DSL scripts: this is where major of our business rules live, but unfortunately we couldn't find any proper mechanisms to have them unit tested.

2. .NET class library: some of complex logic is maintained here. It is fine to write unit tests for medium complex logic. However, I found it's really tricky/even impossible to mock a DomRepository, because it's too tightly coupled by design. I think a good solution for this problem should be injecting an interface of DomRepository, instead of a concrete class as it is currently.

3. Also a .NET class library, that extend Rhetos DSL by defining new keywords: we rarely have to implement this so we don't have much experience on how to organize unit tests for it. Some advice would be more than welcomed.

**Comment by bantolov** [comment]
There are different approaches and technologies that can be used for automated testing, I will write here some methods that I have previously used on Rhetos applications.

We usually create 2 types of tests:

1. Business rules that are implemented in a stand-alone external dll, that does not reference the generated ServerDom, can be tested directly with a classic approach. We use Visual Studio Unit Test Project to directly call the classes and methods of this dll, without a database or a Rhetos server present.
    * For code that reads/writes data through `IRepository` and similar interfaces (this is typically an implementation of some data processing algorithm), the `RepositoryMock` class is written as a simple mock. It is used from the unit tests in `GenericRepositoryWriteTest` class.
2. For business rules that are implemented in DSL scripts, or in an external dll that reference ServerDom, we usually write some kind of integration tests. For this we use Visual Studio Unit Test Project to write and run tests, but each test uses an instance of the Rhetos service (not the web service) and uses it to write some data to the database and check the business rules that should be applied (validations, computed data, and similar).
    * This approach need a database and a deployed Rhetos server (usually inside the working folder of the business application that we are developing), but not IIS. The features are tested by directly using the generated object model, not by web requests.
    * Examples of this kind of tests can be found in Rhetos project <https://github.com/Rhetos/Rhetos>, `CommonConceptsTest.sln` solution:
    * For example, test `ValuesShouldBeSet` verifies that all default property values are set after inserting a new record.
    * Test `InsertInvalidData` verifies if the insert of invalid data is blocked. Note: the "delete" statement should be removed in the business application tests, see notes below.

From this issue's question, we usually test all three types of features with the 2nd type of tests above.

There are some important considerations for the integration tests that we apply to keep their complexity under control:

* Each test should insert its own data and not rely on pre-existing data in the database, or on the data inserted by other tests.
* Each test should clear its data when finished. This is done automatically by `RhetosTestContainer`, see that the constructor parameter `commitChanges` is `false` by default, which means that the SQL transaction will be rolled back at the end of the `using` block.
* The tests should not be affected by the existing data in the database. They can be executed on an empty database (after the application is deployed to it), or on database with some user-entered data.

I haven't tried mocking the repository classes for objects in DSL scripts, so I don't know if there are any complications there. This approach might be useful to avoid having a database available and to write "real" unit tests that depend only on a feature that is tested.

**Comment by bantolov** [comment]
A new demo application for Rhetos is available at <https://github.com/Rhetos/Bookstore>.
It contains the two types of tests that were described above:

1. Standard unit tests - for business rules that are implemented in a stand-alone external dll.
2. Integration tests - for business rules implemented in the DSL scripts.

For more information on build and testing, see the application's Readme.md.
