### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by ngoquoc** [Rhetos/Rhetos#75]
**Is your feature request related to a problem? Please describe.**
Yes. In one of our projects, we have an Angular front end application communicating with a Rhetos backend server. There are 2 scenarios where API versioning matters: 
- We have 2 separate teams working on front end and back end development. That lead to the scenario where deployed front end version is not compatible with back deployed back end version (front end is ahead of back end).
- In production environment, a user may have a cached version of the front end application, and it is not 100% compatible with newest deployed Rhetos back end.

**Describe the solution you'd like**
Rhetos should have a mechanism to manage the API versions. For example, prefix new changes/modules with version number.

**Describe alternatives you've considered**
I think for now we can manually prefix the module names with the proper version number. That may break the module structure, make modules less maintainable; but it can do the job.

**Additional context**
None

**Comment by bantolov** [comment]
API versioning is an important issue, but I don't have a good idea on what can we technically do in Rhetos to help with that. Maybe we could include some metadata in DSL script that will show or hide certain features (Entities, Actions and similar) in specific versions of REST API.

```C
Entity Article
{
    ShortString Title;
    ShortString Description { ApiVersion '2+'; }
}
```

But this could help only in a small number of scenarios.

It we want to allow on old version of API to work after deploying a new version of the application, then developers must be allowed to override the implementation of the old version web methods in such way that they can map old parameters and features to the new application's behavior. This cannot be done automatically.

The only solution I can think of (if a robust API versioning is a critical feature), it to use Rhetos REST as an *internal web API*, and in front of it implement an **API Gateway** as a public interface for other applications and users, that supports versioning. This way developers have full control of modifying old web methods (in the API Gateway) when needed to map the old interface to the new features.

I will close this issue for now, and reopen it if there are new approaches available.
