### ISSUE TITLE
ComputedFrom.AllProperties bug when source is an extension of target

### ISSUE THREAD

**Issue by jbasioli** [Rhetos/Rhetos#82]
**Describe the bug**
Let's say DataStructure 'A' uses SqlQueryable 'B' as its ComputedFrom source and 'B' is an extension of 'A'. If AllProperties is used on aforementioned ComputedFrom, Rhetos will try to create a ForeignKey on property 'ID' from 'A' to 'A' which caues a SqlException (Introducing FOREIGN KEY constraint '...' on table 'A' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.)

**To Reproduce**
```
Module Music
{
	AutodetectSqlDependencies;

	Entity Artist
	{
		ShortString FirstName { Required; MinLength 5; }
		ShortString FamilyName;
		Money ToursRevenue { MinValue 0; }
		Money TotalRevenue { DenyUserEdit; }

		ComputedFrom Music.ComputeArtist
		{
			AllProperties;
			KeepSynchronized;
		}
	}

	SqlQueryable ComputeArtist
	"
		SELECT
			a.ID,
			TotalRevenue = SUM(rs.Revenue) + a.ToursRevenue
		FROM
			Music.Artist a
			LEFT JOIN Music.Record r ON a.ID = r.ArtistID
			LEFT JOIN Music.RecordSales rs ON r.ID = rs.RecordID
		GROUP BY
			a.ID, a.ToursRevenue
	"
	{
		Extends Music.Artist;
		Money TotalRevenue;
	}

	Entity Record
	{
		Reference Artist { Detail; }
	}

	Entity RecordSales
	{
		Reference Record { Detail; }
		ShortString Country;
		Money Revenue;
	}
}
```

**Error message**
Introducing FOREIGN KEY constraint '...' on table 'A' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.

**Expected behavior**
AllProperties should ignore ID if ComputedFrom source is an extension of target.

**Comment by bantolov** [comment]
I agree, we should change the behavior of `AllProperties` concept to detect and exclude this specific situation when `Extends` is copied on an entity that would create a self-reference.

**Comment by nguyenquanghuy031295** [comment]
Hi, in this issue, I'm having problem with **KeepSynchronized** concept
I will use a similar example like above:
```
Module Music
{
	AutodetectSqlDependencies;

	Entity Artist
	{
		ShortString FirstName { Required; MinLength 5; }
		ShortString FamilyName;
		Money ToursRevenue { MinValue 0; }
		Money TotalRevenue { DenyUserEdit; }
	}

	SqlQueryable ComputeArtist
	"
		SELECT
			a.ID,
			TotalRevenue = SUM(rs.Revenue) + a.ToursRevenue
		FROM
			Music.Artist a
			LEFT JOIN Music.Record r ON a.ID = r.ArtistID
			LEFT JOIN Music.RecordSales rs ON r.ID = rs.RecordID
		GROUP BY
			a.ID, a.ToursRevenue
	"
	{
		Extends Music.Artist;
		Money TotalRevenue;
	}

	Entity Record
	{
		Reference Artist { Detail; }
	}

	Entity RecordSales
	{
		Reference Record { Detail; }
		ShortString Country;
		Money Revenue;
	}

	Entity ArtistInfo 
	{
		ComputedFrom Music.ComputeArtist
		{
			AllProperties;
			KeepSynchronized;
		}
	}
}
```

With my example, when a record inserted into **Music.Artist**, it will trigger recompute data in **Music.ArtistInfo**.
But with example in this issue, what is exactly behaviour in **Music.Artist**?
As my knowledge, it would be no "recompute" operation when new record is inserted in **Music.Artist**

Thanks!

**Comment by bantolov** [comment]
> But with example in this issue, what is exactly behaviour in **Music.Artist**?
> As my knowledge, it would be no "recompute" operation when new record is inserted in **Music.Artist**

Inserting a record to Music.Artist should cause recompute on the same entity.
I am not sure, but the current behavior is probably related to creating ChangesOnBaseItemInfo and ComputeForNewBaseItemsInfo in [KeepSynchronizedMacro class](https://github.com/Rhetos/Rhetos/blob/853720dc9d82b9360d392c3956b6f309c94923a8/CommonConcepts/Plugins/Rhetos.Dsl.DefaultConcepts/Computations/KeepSynchronizedInfo.cs#L66).

**Comment by nguyenquanghuy031295** [comment]
Okay, so expectation behaviour is when a record inserted into **Music.Artist** we should recompute on same entity too.
One more thing, I'm using Rhetos on master branch and it built issue's example successfully. (not the **updatedb** process because I'm working on it)

And then when I checked the model file generated, it is like this
![image](https://user-images.githubusercontent.com/23207078/129780880-96d197a4-95a4-484d-9e55-102ab747432b.png)
It has 2 navigation properties pointed to itself and it does not make sense, right ?

As my knowledge because in the **build** process, Rhetos created a concept **UniqueReferenceInfo** and that concept has "Extension" prop same with "Base" prop is **Music.Artist**.
The result I expected is in **Music_Artist** it should only contain navigation prop "Extension_ComputeArtist"

**Comment by bantolov** [comment]
I think that recomputing on the same entity already works automatically. This is an expected behavior.

You are right, the two navigation properties should not be generated. Only Extension_ComputeArtist should remain.
