### ISSUE TITLE
Disable Recompute on deploy

### ISSUE THREAD

**Issue by dragofly** [Rhetos/Rhetos#83]
We have a problem when deploying Rhetos to big dataset because recomputing tables takes up a lot of time (3+ hours) and can break the deploy (TFS build max run time exceed). For now we have been setting NORECOMPUTE on table Common.KeepSynchronizedMetadata in a migration skript. But that is not a good solution for two reasons. Sometimes developers forget to change the guid of the migration skript or are not aware that large recomputation will occur. The other reason is recomputation are skipped on small datasets that so developers need to execute recomputation manually.
Can I suggest a new flag on DeployPackages.exe that skips recomputation so we can switch off that feature when needed.

**Comment by bantolov** [comment]
When this flag is used, DeployPackages should report (EventType.Info) all computed data that should be recomputed but is skipped.
