### ISSUE TITLE
Low level concept for shared code

### ISSUE THREAD

**Issue by ibarban** [Rhetos/Rhetos#87]
**Is your feature request related to a problem? Please describe.**
It would be nice to share the same C# code betwen multiple code snippets inside the rhe scripts.

**Describe the solution you'd like**
Creating a low level concept that should just create a method on a repository class that could be used like this "domRepository.Module.Entity.Method()"

**Describe alternatives you've considered**
An Action could be used but I think that this generates addidtional unneceseray code.
It also exposes the action throw the processing engine so you must take care of the permissions.

**Comment by bantolov** [comment]
I think this will be very useful since we have received a similar feature request from many users.

**Comment by bantolov** [comment]
Solved by #114
